In [1]:
#read the photo an change size
import numpy as np
import cv2
dirName = 'photos/'
imName = 'vespa.jpg'
im = cv2.imread(dirName + imName);
im.size
imgray = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
dst = cv2.resize(imgray, None, fx = 0.5, fy=0.5)
im = cv2.imwrite(dirName + 'vespa.png',dst);
#dst = imgray

In [2]:
#Functions
#creates csv with masks of layers of grays
def segmentImg (im,segArray,path="", cum=True):
    for i in range(len(segArray)):
        ret,thresh1 = cv2.threshold(im,segArray[i],255,cv2.THRESH_BINARY)
        print(thresh1)
        cv2.imwrite( path + "n__" + str(i)  + ".jpg", thresh1);

        #black pen on white paper
        np.savetxt("n__"+str(i)+".csv", 1-thresh1/255, delimiter=",", fmt='%f')
        
        #white pen on black paper
        #np.savetxt("n__"+str(i)+".csv", thresh1/255, delimiter=",", fmt='%f')

In [3]:
segmentImg(dst,[38,60,100,160], path="photos/")

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [255 255 255 ...   0   0   0]
 [255 255 255 ...   0   0   0]
 [255 255 255 ... 255   0   0]]


In [4]:
#### function convert to svg

import linedraw.linedraw as ld

def convertToLinesSvg(inFile):
    #svgDir = "./celeba-dataset/img_align_celeba/svg/"
    svgDir = ""
    #fileNumber = inFile[51:57]
    ld.no_cv = False
    #ld.export_path = svgDir + fileNumber + ".svg"
    ld.export_path = "turing.svg"
    ld.draw_contours = True
    ld.draw_hatch = False
    ld.show_bitmap = True
    ld.resolution = 1024
    ld.hatch_size = 16
    ld.contour_simplify = 2

    #print("converting To Lines")
    lines = ld.sketch(inFile)
    return(lines)

ModuleNotFoundError: No module named 'filters'

In [ ]:
convertToLinesSvg("photos/vespa.png")